### ISSUE TITLE
"swapper master start" not working

### ISSUE THREAD

**Issue by Amauche** [SachaMorard/swapper#1]

**Comment by Amauche** [comment]
I'm on Ubuntu server 18.04 / Docker:
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Wed Jul  3 12:13:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

I used strace command to audit swapper command and I found this:

mmap(NULL, 1439992, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f80868ec000
futex(0xc00005e148, FUTEX_WAKE_PRIVATE, 1) = 1
mkdirat(AT_FDCWD, "/tmp/swapper", 0777) = -1 EEXIST (File exists)
mkdirat(AT_FDCWD, "/tmp/swapper", 0777) = -1 EEXIST (File exists)
openat(AT_FDCWD, "**/tmp/swapper", O_RDONLY**|O_CLOEXEC) = 3
epoll_create1(EPOLL_CLOEXEC)            = 4
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=2258980920, u64=140189991522360}}) = -1 EPERM (**Operation no                                                                                                                         t permitted**)

And this:

epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=2258980920, u64=140189991522360}}) = 0
getsockname(3, {sa_family=AF_INET, sin_port=htons(1207), sin_addr=inet_addr("0.0.0.0")}, [112->16]) = 0
futex(0xc00016e148, FUTEX_WAKE_PRIVATE, 1) = 1
accept4(3, 0xc000071840, [112], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (**Resource temporarily unavailable**)
futex(0xa6f8c0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=999998642}) = 0
futex(0xa6b9f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa6b8f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa6f8c0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=999586935}) = -1 ETIMEDOUT **(Connection timed out)**
futex(0xa6b9f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xa6b8f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xc0000364c8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc00005f648, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xa6f8c0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=7, tv_nsec=998515655}) = 0
futex(0xa6f8c0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=999925374}) = -1 ETIMEDOUT **(Connection timed out)**
futex(0xa6b9f0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xc000036bc8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xc00005f648, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0xa6f8c0, FUTEX_WAIT_PRIVATE, 0, {tv_sec=2, tv_nsec=961827277}) = -1 ETIMEDOUT **(Connection timed out)**

**Comment by Amauche** [comment]
Even after deleting the /tmp/swapper folder, the problem persists.

drwxrwxrwt  10 root root       4096 Jul 10 00:20 tmp/

**Comment by SachaMorard** [comment]
Hello @Amauche 

Why want you to run swapper master inside a docker container ?
Of course, it's possible but I can't see the point. It's a bit like if you would run a kubernetes cluster inside a container...
Swapper is a light binary (written with golang and Mac and Linux compatible) that you have to install on your host, like you do with docker-compose for exemple.
Starting a master launch a [fasthttp](https://github.com/valyala/fasthttp) process listening on port 1207. I don't think you need a container to do so. If you are on Windows, I can compile a swapper specific binary for you, but I can't assure it'll work perfectly.

But anyway, I did a try with a **swapper master container** and it is working on my side.
Here is my Dockerfile
```dockerfile
FROM ubuntu:latest

RUN apt update && apt install curl -y
RUN curl -L "https://github.com/SachaMorard/swapper/releases/download/1.0.0/swapper-$(uname -s)-$(uname -m)" -o /usr/local/bin/swapper
RUN chmod +x /usr/local/bin/swapper

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
EXPOSE 1207
ENTRYPOINT ["/entrypoint.sh"]
```
My entrypoint
```bash
#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset

swapper master start
```

Then I execute:
```bash
docker build -t test .
docker run -p 1207:1207 -d test
```
And everything is ok.

I also test to launch swapper master on an ubuntu vm (on google cloud), and it started perfectly.

**Comment by Amauche** [comment]
Excuse me, I misspoke, I strat swappers from Ubuntu and not from Docker.
Docker is just installed on Ubuntu.

Thank you for the procedure I'll follow it and give you a feedback.

**Comment by Amauche** [comment]
My bad, I have to use --detach to retrieve my shell, otherwise it stays on starting.

![image](https://user-images.githubusercontent.com/2370178/61088779-68367000-a439-11e9-9028-59cc522ce2d2.png)

![image](https://user-images.githubusercontent.com/2370178/61089039-23f79f80-a43a-11e9-90aa-af51207651ea.png)

**Comment by SachaMorard** [comment]
Good news!
Looking forward to have more feedback about swapper.
